import { Injectable } from '@nestjs/common';
import { Movie } from './movie.types';

@Injectable()
export class MovieService {
  getData(): Movie[] {
    return [
      {
        adult: false,
        backdrop_path: '/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg',
        genre_ids: [28, 12, 18],
        id: 558449,
        original_language: 'en',
        original_title: 'Gladiator II',
        overview:
          'Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.',
        popularity: 4201.992,
        poster_path: '/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
        release_date: '2024-11-05',
        title: 'Gladiator II',
        video: false,
        vote_average: 6.778,
        vote_count: 2097,
      },
      {
        adult: false,
        backdrop_path: '/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg',
        genre_ids: [28, 878, 35, 10751],
        id: 939243,
        original_language: 'en',
        original_title: 'Sonic the Hedgehog 3',
        overview:
          'Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.',
        popularity: 4186.749,
        poster_path: '/x7NPbBlrvFRJrpinBSRlMOOUWom.jpg',
        release_date: '2024-12-19',
        title: 'Sonic the Hedgehog 3',
        video: false,
        vote_average: 7.674,
        vote_count: 386,
      },
      {
        adult: false,
        backdrop_path: '/k24eZq5I3jyz4htPkZCRpnUmBzE.jpg',
        genre_ids: [10749, 18],
        id: 1156593,
        original_language: 'es',
        original_title: 'Culpa tuya',
        overview:
          "The love between Noah and Nick seems unwavering despite their parents' attempts to separate them. But his job and her entry into college open up their lives to new relationships that will shake the foundations of both their relationship and the Leister family itself.",
        popularity: 3009.907,
        poster_path: '/1sQA7lfcF9yUyoLYC0e6Zo3jmxE.jpg',
        release_date: '2024-12-26',
        title: 'Your Fault',
        video: false,
        vote_average: 7.1,
        vote_count: 733,
      },
      {
        adult: false,
        backdrop_path: '/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg',
        genre_ids: [12, 10751, 16],
        id: 762509,
        original_language: 'en',
        original_title: 'Mufasa: The Lion King',
        overview:
          'Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.',
        popularity: 2924.518,
        poster_path: '/nHhjqeJcaQKOBCd21c1kV2DK5gm.jpg',
        release_date: '2024-12-18',
        title: 'Mufasa: The Lion King',
        video: false,
        vote_average: 7.5,
        vote_count: 497,
      },
      {
        adult: false,
        backdrop_path: '/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg',
        genre_ids: [28, 878, 12],
        id: 912649,
        original_language: 'en',
        original_title: 'Venom: The Last Dance',
        overview:
          "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
        popularity: 2862.276,
        poster_path: '/aosm8NMQ3UyoBVpSxyimorCQykC.jpg',
        release_date: '2024-10-22',
        title: 'Venom: The Last Dance',
        video: false,
        vote_average: 6.814,
        vote_count: 2194,
      },
      {
        adult: false,
        backdrop_path: '/cjEcqdRdPQJhYre3HUAc5538Gk8.jpg',
        genre_ids: [28, 14, 35],
        id: 845781,
        original_language: 'en',
        original_title: 'Red One',
        overview:
          "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous tracker in a globe-trotting, action-packed mission to save Christmas.",
        popularity: 2249.629,
        poster_path: '/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg',
        release_date: '2024-10-31',
        title: 'Red One',
        video: false,
        vote_average: 7.032,
        vote_count: 1881,
      },
      {
        adult: false,
        backdrop_path: '/uKb22E0nlzr914bA9KyA5CVCOlV.jpg',
        genre_ids: [18, 10749, 14],
        id: 402431,
        original_language: 'en',
        original_title: 'Wicked',
        overview:
          "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
        popularity: 2440.1,
        poster_path: '/2E1x1qcHqGZcYuYi4PzVZjzg8IV.jpg',
        release_date: '2024-11-20',
        title: 'Wicked',
        video: false,
        vote_average: 7.341,
        vote_count: 1074,
      },
      {
        adult: false,
        backdrop_path: '/A6vAMO3myroRfBwSZetY4GVqaW4.jpg',
        genre_ids: [16, 14, 28, 12],
        id: 839033,
        original_language: 'en',
        original_title: 'The Lord of the Rings: The War of the Rohirrim',
        overview:
          '183 years before the events chronicled in the original trilogy, a sudden attack by Wulf, a clever and ruthless Dunlending lord seeking vengeance for the death of his father, forces Helm Hammerhand and his people to make a daring last stand in the ancient stronghold of the Hornburg. Finding herself in an increasingly desperate situation, Héra, the daughter of Helm, must summon the will to lead the resistance against a deadly enemy intent on their total destruction.',
        popularity: 2166.194,
        poster_path: '/hE9SAMyMSUGAPsHUGdyl6irv11v.jpg',
        release_date: '2024-12-05',
        title: 'The Lord of the Rings: The War of the Rohirrim',
        video: false,
        vote_average: 6.6,
        vote_count: 248,
      },
      {
        adult: false,
        backdrop_path: '/tElnmtQ6yz1PjN1kePNl8yMSb59.jpg',
        genre_ids: [16, 12, 10751, 35],
        id: 1241982,
        original_language: 'en',
        original_title: 'Moana 2',
        overview:
          "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
        popularity: 2083.288,
        poster_path: '/m0SbwFNCa9epW1X60deLqTHiP7x.jpg',
        release_date: '2024-11-21',
        title: 'Moana 2',
        video: false,
        vote_average: 7,
        vote_count: 781,
      },
      {
        adult: false,
        backdrop_path: '/fzjH7kt1017R9EckLDmWmH5pGhD.jpg',
        genre_ids: [28, 27, 53],
        id: 970450,
        original_language: 'en',
        original_title: 'Werewolves',
        overview:
          'A year after a supermoon’s light activated a dormant gene, transforming humans into bloodthirsty werewolves and causing nearly a billion deaths, the nightmare resurfaces as the supermoon rises again. Two scientists attempt to stop the mutation but fail, leaving those exposed to the moonlight to once again become feral werewolves. Chaos engulfs the streets as the scientists struggle to reach one of their family homes, now under siege by the savage creatures.',
        popularity: 1670.395,
        poster_path: '/cRTctVlwvMdXVsaYbX5qfkittDP.jpg',
        release_date: '2024-12-04',
        title: 'Werewolves',
        video: false,
        vote_average: 6,
        vote_count: 117,
      },
      {
        adult: false,
        backdrop_path: '/au3o84ub27qTZiMiEc9UYzN74V3.jpg',
        genre_ids: [28, 878, 53],
        id: 1035048,
        original_language: 'en',
        original_title: 'Elevation',
        overview:
          'A single father and two women venture from the safety of their homes to face monstrous creatures to save the life of a young boy.',
        popularity: 1576.453,
        poster_path: '/9knPvD6GLtl1w4pamRomyQKHXyj.jpg',
        release_date: '2024-11-07',
        title: 'Elevation',
        video: false,
        vote_average: 6.3,
        vote_count: 277,
      },
      {
        adult: false,
        backdrop_path: '/dWkdmxIkH9y23s9v1PjQFhTGIwo.jpg',
        genre_ids: [28, 18, 53],
        id: 1043905,
        original_language: 'en',
        original_title: 'Dirty Angels',
        overview:
          "During the United States' 2021 withdrawal from Afghanistan, a group of female soldiers posing as medical relief are sent back in to rescue a group of kidnapped teenagers caught between ISIS and the Taliban.",
        popularity: 1354.815,
        poster_path: '/1y3TG8N8zwwMxqh0qzdyDs3IyCq.jpg',
        release_date: '2024-12-11',
        title: 'Dirty Angels',
        video: false,
        vote_average: 6.562,
        vote_count: 97,
      },
      {
        adult: false,
        backdrop_path: '/rhc8Mtuo3Kh8CndnlmTNMF8o9pU.jpg',
        genre_ids: [28, 53],
        id: 1005331,
        original_language: 'en',
        original_title: 'Carry-On',
        overview:
          'An airport security officer races to outsmart a mysterious traveler forcing him to let a dangerous item slip onto a Christmas Eve flight.',
        popularity: 1228.88,
        poster_path: '/sjMN7DRi4sGiledsmllEw5HJjPy.jpg',
        release_date: '2024-12-05',
        title: 'Carry-On',
        video: false,
        vote_average: 6.958,
        vote_count: 1484,
      },
      {
        adult: false,
        backdrop_path: '/b0itXhS69X33BvLi7uWjUZQs9MB.jpg',
        genre_ids: [27, 878],
        id: 933260,
        original_language: 'en',
        original_title: 'The Substance',
        overview:
          'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
        popularity: 1086.872,
        poster_path: '/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
        release_date: '2024-09-07',
        title: 'The Substance',
        video: false,
        vote_average: 7.1,
        vote_count: 3056,
      },
      {
        adult: false,
        backdrop_path: '/lntyt4OVDbcxA1l7LtwITbrD3FI.jpg',
        genre_ids: [10749, 18],
        id: 1010581,
        original_language: 'es',
        original_title: 'Culpa mía',
        overview:
          "Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
        popularity: 1054.65,
        poster_path: '/w46Vw536HwNnEzOa7J24YH9DPRS.jpg',
        release_date: '2023-06-08',
        title: 'My Fault',
        video: false,
        vote_average: 7.9,
        vote_count: 3326,
      },
      {
        adult: false,
        backdrop_path: '/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg',
        genre_ids: [16, 14, 12],
        id: 823219,
        original_language: 'lv',
        original_title: 'Straume',
        overview:
          'A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.',
        popularity: 1109.247,
        poster_path: '/imKSymKBK7o73sajciEmndJoVkR.jpg',
        release_date: '2024-01-30',
        title: 'Flow',
        video: false,
        vote_average: 8.4,
        vote_count: 563,
      },
      {
        adult: false,
        backdrop_path: '/A28EE0vgHrB0OdoxWWMfgfyEoYn.jpg',
        genre_ids: [80, 53, 28],
        id: 1276945,
        original_language: 'nl',
        original_title: 'Ferry 2',
        overview:
          "After losing his drug empire, Ferry Bouman has found a measure of peace away from Brabant's criminal underworld — until his past catches up to him.",
        popularity: 873.984,
        poster_path: '/8pwdnL3pEISIN1EGmwZzU6hpNVk.jpg',
        release_date: '2024-12-19',
        title: 'Ferry 2',
        video: false,
        vote_average: 5.7,
        vote_count: 76,
      },
      {
        adult: false,
        backdrop_path: '/6lE2e6j8qbtQR8aHxQNJlwxdmKV.jpg',
        genre_ids: [28, 80, 53],
        id: 974453,
        original_language: 'en',
        original_title: 'Absolution',
        overview:
          'An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis.  Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.',
        popularity: 836.071,
        poster_path: '/2MeQG5Vq8rUnRAa463BZe5GNhVk.jpg',
        release_date: '2024-10-31',
        title: 'Absolution',
        video: false,
        vote_average: 5.9,
        vote_count: 230,
      },
      {
        adult: false,
        backdrop_path: '/uWOJbarUXfVf6B4o0368dh138eR.jpg',
        genre_ids: [18, 14, 27],
        id: 426063,
        original_language: 'en',
        original_title: 'Nosferatu',
        overview:
          'A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.',
        popularity: 952.121,
        poster_path: '/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg',
        release_date: '2024-12-25',
        title: 'Nosferatu',
        video: false,
        vote_average: 6.8,
        vote_count: 609,
      },
      {
        adult: false,
        backdrop_path: '/6amNYUYvoKsZbg8vE00Yzt9Xn7H.jpg',
        genre_ids: [28, 35, 878],
        id: 533535,
        original_language: 'en',
        original_title: 'Deadpool & Wolverine',
        overview:
          'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
        popularity: 856.096,
        poster_path: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        release_date: '2024-07-24',
        title: 'Deadpool & Wolverine',
        video: false,
        vote_average: 7.7,
        vote_count: 6264,
      },
    ];
  }
}
